### ISSUE TITLE
The preprocessed dataset

### ISSUE THREAD

**Issue by 649459021** [DengPingFan/FSGAN#1]
I can't find the preprocessed dataset in google drive. The FS2K.zip in google drive folder seems to be unaligned?

**Comment by ZhengPeng7** [comment]
Hi, as we [mentioned](https://github.com/DengPingFan/FSGAN#dataset) in README, you can use the preprocessing codes provided [here](https://drive.google.com/drive/folders/1DpfkwOOb5RafXw0rmKTrCEPGFvoB_dP1) to obtain the exact aligned results.

We followed the [APDrawingGAN](https://github.com/yiranran/APDrawingGAN) to employ key point detection (MTCNN) and human segmentation (U-2-Net) sequentially. But codes in [APDrawingGAN](https://github.com/yiranran/APDrawingGAN) don't have an up-to-date preprocessing that's easy to use. So we strongly recommend you to directly use our preproc codes which are in the latest PyTorch version.

**Comment by ZhengPeng7** [comment]
You can also directly download the [FS2K_preproc.zip](https://drive.google.com/drive/folders/1DpfkwOOb5RafXw0rmKTrCEPGFvoB_dP1) (preprocessing codes and the preprocessed data which have been split into train/test sets).

**Comment by 649459021** [comment]
> You can also directly download the [FS2K_preproc.zip](https://drive.google.com/drive/folders/1DpfkwOOb5RafXw0rmKTrCEPGFvoB_dP1) (preprocessing codes and the preprocessed data which have been split into train/test sets).

Thank you very much for your patient reply. 
In addition, the input image size of model is resized from 250 or 318(original dataset size) to 512. The input image becomes a little blurry. Whether resize to 256 is more appropriate？

**Comment by ZhengPeng7** [comment]
You are welcome. Actually, you can take a look at the Table. 1 in the [original paper](https://arxiv.org/pdf/2112.15439.pdf), the resolution is `299.74±95.07 × 273.56±38.67`. Thus, though the resolution of more images in the dataset is closer to `256x256`, we want to keep more information in those images of high resolution.
You can also try resizing them to `256x256` in preproc codes and use them for training, I think the results will be similar to the existing ones.

**Comment by 649459021** [comment]
> You are welcome. Actually, you can take a look at the Table. 1 in the [original paper](https://arxiv.org/pdf/2112.15439.pdf), the resolution is `299.74±95.07 × 273.56±38.67`. Thus, though the resolution of more images in the dataset is closer to `256x256`, we want to keep more information in those images of high resolution. You can also try resizing them to `256x256` in preproc codes and use them for training, I think the results will be similar to the existing ones.

Thanks so much again. I will try both sizes in experiment.
