### ISSUE TITLE
What about S2I?

### ISSUE THREAD

**Issue by Sherlockyyf** [DengPingFan/FSGAN#2]
This code seems to only be used for I2S task, what about the S2I task? Do I need to change the configurations somewhere? I really appreciate it if the authors could reply. Thank you!

**Comment by ZhengPeng7** [comment]
You need to check the value of "--which_direction" in `options/base_option.py` and some other changes in input-output. But to be frank, this project is too big to make it easy to adapt then. The overall structure of this project is based on the existing [APDrawingGAN](https://github.com/yiranran/APDrawingGAN), you can refer to it for detailed modifications if needed.
