### ISSUE TITLE
您好，我是一个GAN的初学者，论文中有不明白的地方想请教您一下

### ISSUE THREAD

**Issue by NENUQianWeijie** [DengPingFan/FSGAN#3]
![9ad87bfa3673ef5e2839a17d8291c3d](https://github.com/DengPingFan/FSGAN/assets/100955056/2c871f9d-529b-4ddc-beda-bb1cd0a8f647)
想请教您一下论文中这个epoch在代码中是对应哪个地方呢

**Comment by ZhengPeng7** [comment]
去`train.py`就能找, 这里: [link](https://github.com/DengPingFan/FSGAN/blob/8a22a6a64a7b7e24ee68030ac4cc563d63c8de18/train.py#L20).
定义在配置文件里: [link](https://github.com/DengPingFan/FSGAN/blob/8a22a6a64a7b7e24ee68030ac4cc563d63c8de18/options/train_options.py), 可自行修改.

**Comment by NENUQianWeijie** [comment]
太感谢您的回复了，真的是太感谢了，我这一块还是有点没看懂，具体参数设置还想向您请教一下
1.λfm，λper，λ1，λsty对应train_options.py中哪几个参数呢？
2.生成器和判别器的学习率是在哪里设置参数呢？
3.在S2I任务中，看到您使用了两组参数分别训练了两个不同的阶段，这个是怎么做到的呢？具体是要在哪里设置这两组参数呢？
4.在S2I任务中，先将epoch设置为400，然后在epoch=250后冻结facial components synthesis module，这个250是怎么设置的呢？
5.unet_512是在哪里使用的呢？我在论文中没有找到对应的地方，这个是应该放在checkpoints目录下吗？

**Comment by ZhengPeng7** [comment]
1. 所需的loss可以参考[这里](https://github.com/DengPingFan/FSGAN/blob/8a22a6a64a7b7e24ee68030ac4cc563d63c8de18/models/apdrawing_gan_model.py#L24)定义以及[这里](https://github.com/DengPingFan/FSGAN/blob/8a22a6a64a7b7e24ee68030ac4cc563d63c8de18/models/apdrawing_gan_model.py#L258)和`train_options.py`里的赋值, 结合着看应该更清晰. 具体的你可以再看下文章里的几个loss的公式, 还是挺清晰的, 例如$L_{per}$是VGG loss.
2. G和D的学习率在网络中设置的, 例如[这里](https://github.com/DengPingFan/FSGAN/blob/8a22a6a64a7b7e24ee68030ac4cc563d63c8de18/models/apdrawing_gan_model.py#L104)和[这里](https://github.com/DengPingFan/FSGAN/blob/8a22a6a64a7b7e24ee68030ac4cc563d63c8de18/models/apdrawing_gan_model.py#L108C7-L108C7).
3. 说实话这个proj的代码一开始我没有参与, 所以有部分设定的初始想法我也不清楚, 而且对于部分类似epoch的设置后来我有调优. 此外, 这个repo当时的代码有点过于庞大, 之后弄了很多还是感觉比较臃肿, 有的东西说实话可能确实就不太记得了. 而且这个repo主要是做image2sketch的. 如果碰到有的参数不理解, 可以去参考[APDrawingGAN](https://github.com/yiranran/APDrawingGAN), 网络结构方面主要其实就是基于APDrawingGAN的, 文件也直接体现了. 如果再有, 你也可以邮件询问请教Dr. Zilin huang, 也就是2nd author.
4. epoch是当时实验的一些细节, 就是通过尝试来设的一个大概的值, 你也可以调整. 
5. UNet 你可以看到`base_options.py`里的`netG`, 就是用了UNet_xx. 当然, 更具体的你可以看[这里](https://github.com/DengPingFan/FSGAN/blob/8a22a6a64a7b7e24ee68030ac4cc563d63c8de18/models/networks.py#L89), 有几种XXNet_xx选项, 这里体现了是如何使用的, 即每个小enc+dec都是一个UNet.

**Comment by NENUQianWeijie** [comment]
真的太感谢老师的回复了，我读您论文的时候，看网络结构图特别明晰，但是阅读代码时有点没读懂，我想要把代码和论文中的模型结构图对应起来，应该是以一个怎样的顺序去阅读models文件夹下的这些文件呢

**Comment by NENUQianWeijie** [comment]
我应该在哪里查询Dr. Zilin huang老师的邮箱呢

**Comment by ZhengPeng7** [comment]
客气啦, 都是同学. 对, 确实比较复杂, 我当时也看了好久😂模型逻辑不复杂, 代码比较工程化得庞大了, 主要也是因为沿用的APDrawingGAN的 (它比较复杂), 大部分其实都是对应的, 你也可以去看看它. 邮箱的话论文或者出版社文章主页里有写吧, 你可以看下README的Springer和MIR的, 是有的.

**Comment by NENUQianWeijie** [comment]
太感谢您的回复了，我看了APDrawingGAN的论文，大概理解了五个并行的GAN网络这部分是由apdrawing_gan_model.py这个文件实现的，但是我没找到论文中G1，G2和风格向量这部分的代码，想请教您一下这部分的代码在哪里呢

**Comment by ZhengPeng7** [comment]
Hi, 风格向量你可以看[这里](https://github.com/DengPingFan/FSGAN/blob/8a22a6a64a7b7e24ee68030ac4cc563d63c8de18/data/aligned_dataset.py#L97), 也就是三种风格的标签labe初始化, 应该就能理解了. 至于G1, G2, 我明天再细看下回复你哈。

**Comment by NENUQianWeijie** [comment]
不好意思，没能及时回您你，太感谢您的回复了，实在是麻烦您了
