### ISSUE TITLE
gpu大小

### ISSUE THREAD

**Issue by ludandandan** [DengPingFan/FSGAN#4]
你好，Our model can only train on GPU >=32 GB at present，请问是必须单卡就有32G吗，我现在有两张24G的4096的卡，训练的时候设置了--gpu_ids 0,1 ,但是发现只用上了0号卡，并且报out of memeory

**Comment by ZhengPeng7** [comment]
是的, 24G的貌似确实是没法训... 因为现batchsize已经很小了, 即使多卡, 0号卡的占用显存是不降的.

**Comment by ludandandan** [comment]
嗷嗷，好的，谢谢回复～
